# Generated by Django 3.2.9 on 2021-11-15 19:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('available_products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Unavailable', 'unavailble')], default='Availble', max_length=11),
            preserve_default=False,
        ),
    ]
