# Generated by Django 3.2.9 on 2021-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211115_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tag_product', to='product.Tag'),
        ),
    ]
