# Generated by Django 3.2.9 on 2021-11-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_remove_cartitem_price'),
        ('user', '0006_alter_seller_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='product',
        ),
        migrations.AddField(
            model_name='seller',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
