# Generated by Django 3.2.9 on 2021-11-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20211107_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('natinal_code', models.PositiveIntegerField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField(max_length=11)),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Undefind', 'undefind')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('product', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
