# Generated by Django 3.2.9 on 2021-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211107_1944'),
        ('user', '0002_auto_20211108_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
