# Generated by Django 3.2.9 on 2021-11-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20211108_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together=set(),
        ),
    ]
