# Generated by Django 3.2.9 on 2021-11-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20211108_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
